import { Runeword } from "@/typings/runeword";

export const Runewords: Record<string, Runeword> = {
  stealth: {
    key: "stealth",
    runes: ["tal", "eth"],
    name: {
      es: "Sigilo",
      en: "Stealth",
    },
    level: {
      es: "Nv. 17",
      en: "Lv. 17",
    },
    requires: {
      es: ["Armaduras"],
      en: ["Armors"],
    },
    details: {
      es: [
        "Correr/andar un +25% más Rápido",
        "Velocidad de Lanzamiento un +25% más Rápido",
        "Recuperación de Golpe un +25% más Rápida",
        "+6 de Destreza",
        "+15% de Regeneración de maná",
        "+15 de Aguante Máximo",
        "+30% de Resistencia al Veneno",
        "Daño Mágico Reducido en 3 p.",
      ],
      en: [
        "Magic Damage Reduced By 3",
        "+6 To Dexterity",
        "+15 To Maximum Stamina",
        "Poison Resist +30%",
        "Regenerate Mana 15%",
        "25% Faster Run/Walk",
        "25% Faster Cast Rate",
        "25% Faster Hit Recovery",
      ],
    },
    expansion: "lod",
    references: {
      es: "https://diablo.fandom.com/wiki/Stealth_Rune_Word",
      en: "https://diablo.fandom.com/wiki/Stealth_Rune_Word",
    },
  },
  leaf: {
    key: "leaf",
    runes: ["tir", "ral"],
    name: {
      es: "Hoja",
      en: "Leaf",
    },
    level: {
      es: "Nv. 19",
      en: "Lv. 19",
    },
    requires: {
      es: ["Bastones"],
      en: ["Staves"],
    },
    details: {
      es: [
        "Añade 5-30 de Daño de Fuego",
        "+3 a las Habilidades de Fuego",
        "+3 para Descarga de fuego (solo Hechicera)",
        "+3 para Infierno (solo Hechicera)",
        "+3 para Calor (solo Hechicera)",
        "+2 al mana Tras Cada Muerte",
        "+2-198 de Defensa (+2 por Nivel)",
        "Resistencia al Frio +33%",
      ],
      en: [
        "Adds 5-30 Fire Damage",
        "+3 To Fire Skills",
        "+3 To Fire Bolt (Sorceress Only)",
        "+3 To Inferno (Sorceress Only)",
        "+3 To Warmth (Sorceress Only)",
        "+2 To Mana After Each Kill",
        "+ (2 Per Character Level) +2-198 To Defense (Based On Character Level)",
        "Cold Resist +33%",
      ],
    },
    expansion: "lod",
    references: {
      es: "https://diablo.fandom.com/wiki/Leaf_Rune_Word",
      en: "https://diablo.fandom.com/wiki/Leaf_Rune_Word",
    },
  },
  unbending_will: {
    key: "unbending_will",
    runes: ["fal", "io", "ith", "eld", "el", "hel"],
    name: {
      es: "Voluntad De Hierro",
      en: "Unbending Will",
    },
    level: {
      es: "Nv. 41",
      en: "Lv. 41",
    },
    requires: {
      es: ["Espadas"],
      en: ["Swords"],
    },
    details: {
      es: [
        "18% de probabilidad de lanzar Burla de nivel 18 al golpear",
        "+3 p. a las habilidades de combate (solo bárbaro)",
        "+20-30% de velocidad de ataque (varia)",
        "+300-350% de daño mejorado (varia)",
        "+9 p. de daño máximo",
        "+50 p. de índice de ataque",
        "+75% de daño contra muertos vivientes",
        "+50 p. de índice de ataque contra muertos vivientes",
        "8-10% de vida robada por golpe (varia)",
        "Impide que los monstruos se curen",
        "+10 p. de fuerza",
        "+10 p. de vitalidad",
        "Daño reducido en 8 p.",
        "+1 p. de radio de visión",
        "Requisitos -20%",
      ],
      en: [
        "18% Chance to cast Level 18 Taunt on striking",
        "+3 To Combat Skills (Barbarian Only)",
        "+20-30% Increased Attack Speed (varies)",
        "+300-350% Enhanced Damage (varies)",
        "+9 To Maximum Damage",
        "+50 To Attack Rating",
        "+75% Damage to Undead",
        "+50 Attack Rating Against Undead",
        "8-10% Life Stolen Per Hit (varies)",
        "Prevent Monster Heal",
        "+10 To Strength",
        "+10 To Vitality",
        "Damage Reduced By 8",
        "+1 Light Radius",
        "Requirements -20%",
      ],
    },
    expansion: "lod",
    references: {
      es: "https://diablo.fandom.com/wiki/Unbending_Will_Rune_Word",
      en: "https://diablo.fandom.com/wiki/Unbending_Will_Rune_Word",
    },
  },
  plague: {
    key: "plague",
    runes: ["cham", "shael", "um"],
    name: {
      es: "Plaga",
      en: "Plague",
    },
    level: {
      es: "Nv. 55",
      en: "Lv. 55",
    },
    requires: {
      es: ["Dagas", "Garras", "Espadas"],
      en: ["Daggers", "Katars", "Swords"],
    },
    details: {
      es: [
        "20% de probabilidad de lanzar Reducción de Resistencia de nivel 12 al recibir un golpe",
        "25% de probabilidad de lanzar Nova de Veneno de nivel 15 al golpear",
        "Aura Purificación de nivel 13-17 si está equipado (varía)",
        "+1-2 p. a todas las habilidades (varía)",
        "+20% de velocidad de ataque",
        "+220-320% de daño mejorado (varía)",
        "-23% de resistencia enemiga al veneno",
        "0,3% (0-29,7) de probabilidad de azote mortal [según el nivel del personaje]",
        "+25% de probabilidad de sangrado",
        "Congela al objetivo +3",
      ],
      en: [
        "20% Chance To Cast Level 12 Lower Resist When Struck",
        "25% Chance To Cast Level 15 Poison Nova On Striking",
        "Level 13-17 Cleansing Aura When Equipped (varies)",
        "+1-2 To All Skills",
        "+20% Increased Attack Speed",
        "+220-320% Enhanced Damage (varies)",
        "-23% To Enemy Poison Resistance",
        "0.3% (0-29.7) Deadly Strike (Based On Character Level)",
        "+25% Chance of Open Wounds",
        "Freezes Target +3",
      ],
    },
    expansion: "lod",
    references: {
      es: "https://diablo.fandom.com/wiki/Plague_Rune_Word",
      en: "https://diablo.fandom.com/wiki/Plague_Rune_Word",
    },
  },
  zephyr: {
    key: "zephyr",
    runes: ["ort", "eth"],
    name: {
      es: "Céfiro",
      en: "Zephyr",
    },
    level: {
      es: "Nv. 21",
      en: "Lv. 21",
    },
    requires: {
      es: ["Arcos", "Ballestas"],
      en: ["Bows", "Crossbows"],
    },
    details: {
      es: [
        "+33% Daño Perfeccionado",
        "+66 Puntuación de Ataque",
        "Añade 1-50 de Daño de Relámpago",
        "-25% Defensa del Objetivo por Golpe",
        "+25 Defensa",
        "25% Correr/Andar Mas Rápido",
        "25% Velocidad de Ataque Aumentada",
        "7% Posibilidad de Lanzar el Nivel 1 Tornado al Recibir un Golpe",
      ],
      en: [
        "+33% Enhanced Damage",
        "+66 To Attack Rating",
        "Adds 1-50 Lightning Damage",
        "-25% Target Defense",
        "+25 Defense",
        "25% Faster Run/Walk",
        "25% Increased Attack Speed",
        "7% Chance To Cast Level 1 Twister When Struck",
      ],
    },
    expansion: "lod",
    references: {
      es: "https://diablo.fandom.com/wiki/Zephyr_Rune_Word",
      en: "https://diablo.fandom.com/wiki/Zephyr_Rune_Word",
    },
  },
  chains_of_honor: {
    key: "chains_of_honor",
    runes: ["dol", "um", "ber", "ist"],
    name: {
      es: "Cadenas de Honor",
      en: "Chains of Honor",
    },
    level: {
      es: "Nv. 63",
      en: "Lv. 63",
    },
    requires: {
      es: ["Armaduras"],
      en: ["Armors"],
    },
    details: {
      es: [
        "+2 a Todas las Habilidades",
        "+200% Daño a Demonios",
        "+100% Daño a Muertos Vivientes",
        "8% Vida Robada por Impacto",
        "+70% Defensa Mejorada",
        "+20 de Fuerza",
        "Repostar Vida +7",
        "Todas las Resistencias +65",
        "Daño Reducido en 8%",
        "+25% de Probabilidad de Encontrar Objetos Mágicos",
      ],
      en: [
        "+2 To All Skills",
        "+200% Damage To Demons",
        "+100% Damage To Undead",
        "8% Life Stolen Per Hit",
        "+70% Enhanced Defense",
        "+20 To Strength",
        "Replenish Life +7",
        "All Resistances +65",
        "Physical Damage Received Reduced By 8%",
        "25% Better Chance of Getting Magic Items",
      ],
    },
    expansion: "lod",
    references: {
      es: "https://diablo.fandom.com/wiki/Chains_of_Honor_Rune_Word",
      en: "https://diablo.fandom.com/wiki/Chains_of_Honor_Rune_Word",
    },
  },
  nadir: {
    key: "nadir",
    runes: ["nef", "tir"],
    name: {
      es: "Nadir",
      en: "Nadir",
    },
    level: {
      es: "Nv. 13",
      en: "Lv. 13",
    },
    requires: {
      es: ["Yelmos"],
      en: ["Helmets"],
    },
    details: {
      es: [
        "+50% de Defensa Mejorada",
        "+10 de Defensa",
        "+30 de Defensa Contra Misiles",
        "+5 de Fuerza",
        "+2 p. al maná Tras Cada Asesinato",
        "-33% de Oro Extra de los Monstruos",
        "-3 de Radio de Visión",
        "Capa de Sombras de Nivel 13 (9 Cargas)",
      ],
      en: [
        "+50% Enhanced Defense",
        "+10 Defense",
        "+30 Defense vs. Missile",
        "Level 13 Cloak of Shadows (9 Charges)",
        "+2 To Mana After Each Kill",
        "+5 To Strength",
        "-33% Extra Gold From Monsters",
        "-3 To Light Radius",
      ],
    },
    expansion: "lod",
    references: {
      es: "https://diablo.fandom.com/wiki/Nadir_Rune_Word",
      en: "https://diablo.fandom.com/wiki/Nadir_Rune_Word",
    },
  },
  ritual: {
    key: "ritual",
    runes: ["amn", "shael", "ohm"],
    name: {
      es: "Ritual",
      en: "Ritual",
    },
    level: {
      es: "Nv. 57",
      en: "Lv. 57",
    },
    requires: {
      es: ["Dagas"],
      en: ["Daggers"],
    },
    details: {
      es: [
        "13% de probabilidad de lanzar el nivel 1 de Muerte de sigilo al recibir un azote",
        "+20% de velocidad de ataque aumentada",
        "+200-270% de daño aumentado (varia)",
        "+150-250% de daño a los demonios (varia)",
        "+200-260% de bonificación a la puntuación de ataque (varia)",
        "+3-5 de vida después de cada muerte (varia)",
        "Los monstruos eliminados descansan en paz",
        "7% de vida robada por impacto",
        "+20% de velocidad de ataque aumentada",
        "+50% de daño aumentado",
      ],
      en: [
        "13% Chance to cast level 1 Sigil Death when struck",
        "+40% Increased Attack Speed",
        "+250-320% Enhanced Damage",
        "+150-250% Damage to Demons",
        "+200-260% Bonus to Attack Rating",
        "+3-5 Life after each Kill",
        "Slain Monsters Rest in Peace",
        "7% Life stolen per hit",
      ],
    },
    expansion: "row",
    references: {
      es: "https://diablo2.io/runewords/ritual-t1673938.html",
      en: "https://diablo2.io/runewords/ritual-t1673938.html",
    },
  },
  call_to_arms: {
    key: "call_to_arms",
    runes: ["amn", "ral", "mal", "ist", "ohm"],
    name: {
      es: "Llamado a las Armas",
      en: "Call to Arms",
    },
    level: {
      es: "Nv. 51",
      en: "Lv. 51",
    },
    requires: {
      es: ["Armas"],
      en: ["Weapons"],
    },
    details: {
      es: [
        "+1 a Todas las Habilidades",
        "+40% Velocidad de Ataque aumentada",
        "+250-290% Daño Mejorado (varia)",
        "Añade 5-30 Daño de Fuego",
        "7% Vida Robada por Impacto",
        "+2-6 a Instrucción de Batalla (varia)",
        "+1-6 a Ordenes de Batalla (varia)",
        "+1-4 a Grito de Batalla (varia)",
        "Evita la Curación del Monstruo",
        "Repostar Vida +12",
        "+30% de Probabilidad de Encontrar Objetos Mágicos",
      ],
      en: [
        "+1 To All Skills",
        "+40% Increased Attack Speed",
        "+250-290% Enhanced Damage",
        "Adds 5-30 Fire Damage",
        "7% Life Stolen Per Hit",
        "+2-6 To Battle Command",
        "+1-6 To Battle Orders",
        "+1-4 To Battle Cry",
        "Prevent Monster Heal",
        "Replenish Life +12",
        "30% Better Chance of Getting Magic Items",
      ],
    },
    expansion: "lod",
    references: {
      es: "https://diablo.fandom.com/wiki/Call_to_Arms_Rune_Word",
      en: "https://diablo.fandom.com/wiki/Call_to_Arms_Rune_Word",
    },
  },
  authority: {
    key: "authority",
    runes: ["hel", "shael", "ral"],
    name: {
      es: "Autoridad",
      en: "Authority",
    },
    level: {
      es: "Nv. 29",
      en: "Lv. 29",
    },
    requires: {
      es: ["Armaduras"],
      en: ["Armors"],
    },
    details: {
      es: [
        "2% de probabilidad de lanzar el nivel 10 de Escudo psíquico al recibir un azote",
        "10% de probabilidad de lanzar el nivel 15 de Cadena de miasmas al impactar",
        "+2 a los niveles de habilidad de Brujo",
        "+40-60% de daño aumentado (varia)",
        "Requisitos -15%",
        "+20% de recuperación de impacto más rápida",
        "Resistencia al fuego +30%",
      ],
      en: [
        "2% Chance to cast level 10 Psychic Ward when struck",
        "10% Chance to cast level 15 Miasma Chain on striking",
        "+2 to Warlock Skill Levels",
        "+40-60% Enhanced Damage",
        "Requirements -15%",
        "+20% Faster Hit Recovery",
        "Fire Resist +30%",
      ],
    },
    expansion: "row",
    references: {
      es: "https://diablo2.io/runewords/authority-t1673934.html",
      en: "https://diablo2.io/runewords/authority-t1673934.html",
    },
  },
  bone: {
    key: "bone",
    runes: ["sol", "um", "um"],
    name: {
      es: "Hueso",
      en: "Bone",
    },
    level: {
      es: "Nv. 47",
      en: "Lv. 47",
    },
    requires: {
      es: ["Armaduras"],
      en: ["Armors"],
    },
    details: {
      es: [
        "15% de Posibilidades de Lanzar el nivel 10 Armadura de Hueso al Recibir un Azote",
        "15% de Posibilidades de Lanzar el nivel 10 Lanza Osea al Azotar",
        "+2 a los niveles de Habilidad de la Nigromante",
        "100-150 de Mana (varía)",
        "Todas las Resistencias +30",
        "Daño Reducido en 7",
      ],
      en: [
        "15% Chance To Cast Level 10 Bone Armor When Struck",
        "15% Chance To Cast Level 10 Bone Spear On Striking",
        "+2 To Necromancer Skill Levels",
        "+100-150 To Mana (varies)",
        "All Resistances +30",
        "Damage Reduced By 7",
      ],
    },
    expansion: "lod",
    references: {
      es: "https://diablo.fandom.com/wiki/Bone_Rune_Word",
      en: "https://diablo.fandom.com/wiki/Bone_Rune_Word",
    },
  },
  kingslayer: {
    key: "kingslayer",
    runes: ["mal", "um", "gul", "fal"],
    name: {
      es: "Regicida",
      en: "Kingslayer",
    },
    level: {
      es: "Nv. 53",
      en: "Lv. 53",
    },
    requires: {
      es: ["Hachas", "Espadas"],
      en: ["Axes", "Swords"],
    },
    details: {
      es: [
        "+30% Velocidad de Ataque Aumentada",
        "+230-270% Daño Mejorado (varía)",
        "-25% Defensa del Objetivo",
        "20% Bonificación al Ataque",
        "33% Posibilidad de Golpe Triturador",
        "50% Posibilidad de Heridas Abiertas",
        "+1 a Venganza",
        "Evita la Curación del Monstruo",
        "+10 de Fuerza",
        "40% Oro Extra de los Monstruos",
      ],
      en: [
        "+30% Increased Attack Speed",
        "+230-270% Enhanced Damage",
        "-25% Target Defense",
        "20% Bonus To Attack Rating",
        "+33% Chance of Crushing Blow",
        "+50% Chance of Open Wounds",
        "+1 To Vengeance",
        "Prevent Monster Heal",
        "+10 To Strength",
        "40% Extra Gold From Monsters",
      ],
    },
    expansion: "lod",
    references: {
      es: "https://diablo.fandom.com/wiki/Kingslayer_Rune_Word",
      en: "https://diablo.fandom.com/wiki/Kingslayer_Rune_Word",
    },
  },
  strength: {
    key: "strength",
    runes: ["amn", "tir"],
    name: {
      es: "Fuerza",
      en: "Strength",
    },
    level: {
      es: "Nv. 25",
      en: "Lv. 25",
    },
    requires: {
      es: ["Armas Melee"],
      en: ["Melee Weapons"],
    },
    details: {
      es: [
        "+35% Daño Mejorado",
        "25% Posibilidad de Golpe Triturador",
        "7% Vida Robada Por Impacto",
        "+20 Fuerza",
        "+10 Vitalidad",
        "+2 al mana Tras Cada Muerte",
      ],
      en: [
        "35% Enhanced Damage",
        "+25% Chance Of Crushing Blow",
        "7% Life Stolen Per Hit",
        "+2 To Mana After Each Kill",
        "+20 To Strength",
        "+10 To Vitality",
      ],
    },
    expansion: "lod",
    references: {
      es: "https://diablo.fandom.com/wiki/Strength_Rune_Word",
      en: "https://diablo.fandom.com/wiki/Strength_Rune_Word",
    },
  },
  fortitude: {
    key: "fortitude",
    runes: ["el", "sol", "dol", "lo"],
    name: {
      es: "Fortaleza",
      en: "Fortitude",
    },
    level: {
      es: "Nv. 59",
      en: "Lv. 59",
    },
    requires: {
      es: ["Armaduras", "Armas"],
      en: ["Armors", "Weapons"],
    },
    details_on: [
      {
        key: "weapon",
        name: {
          es: "Arma",
          en: "Weapon",
        },
        items: {
          es: [
            "20% de Posibilidades de Lanzar el Nivel 15 Armadura Gélida al recibir un Azote",
            "+25% Velocidad de Lanzamiento Mayor",
            "+300% Daño Mejorado",
            "+9 al Daño Mínimo",
            "+50 de Puntuación de Ataque",
            "+20% Azote Mortal",
            "El Impacto hace que el Monstruo Huya 25%",
            "+200% Defensa Perfeccionada",
            "+XX de vida [1 a 1.5 por Nivel] (varia)",
            "Todas las resistencias +20-30 (varia)",
            "12% el Daño Infligido Repercute en el Mana",
            "+1 al Radio de Luz",
          ],
          en: [
            "20% Chance To Cast Level 15 Chilling Armor when Struck",
            "+25% Faster Cast Rate",
            "+300% Enhanced Damage",
            "+200% Enhanced Defense",
            "+XX To Life (Based on Character Level) (varies)",
            "All Resistances +25-30 (varies)",
            "12% Damage Taken Goes To Mana",
            "+1 To Light Radius",
            "+9 To Minimum Damage",
            "+50 To Attack Rating",
            "20% Deadly Strike",
            "Hit Causes Monster To Flee 25%",
          ],
        },
      },
      {
        key: "armor",
        name: {
          es: "Armadura",
          en: "Armor",
        },
        items: {
          es: [
            "20% de Posibilidades de Lanzar el Nivel 15 Armadura Gélida al recibir un Azote",
            "+25% Velocidad de Lanzamiento Mayor",
            "+300% Daño Mejorado",
            "+200% Defensa Perfeccionada",
            "+15 Defensa",
            "+XX de vida [1 a 1.5 por Nivel] (varia)",
            "Repostar vida +7",
            "5% a la Resistencia Máxima a los Relámpagos",
            "Todas las resistencias +20-30 (varia)",
            "Daño reducido por 7",
            "12% el Daño Infligido Repercute en el Mana",
            "+1 al Radio de Luz",
          ],
          en: [
            "20% Chance To Cast Level 15 Chilling Armor when Struck",
            "+25% Faster Cast Rate",
            "+300% Enhanced Damage",
            "+200% Enhanced Defense",
            "+XX To Life (Based on Character Level) (varies)",
            "All Resistances +25-30 (varies)",
            "12% Damage Taken Goes To Mana",
            "+1 To Light Radius",
            "+15 Defense",
            "Replenish Life +7",
            "+5% To Maximum Lightning Resist",
            "Damage Reduced By 7",
          ],
        },
      },
    ],
    expansion: "lod",
    references: {
      es: "https://diablo.fandom.com/wiki/Fortitude_Rune_Word",
      en: "https://diablo.fandom.com/wiki/Fortitude_Rune_Word",
    },
  },
  lore: {
    key: "lore",
    runes: ["ort", "sol"],
    name: {
      es: "Acervo",
      en: "Lore",
    },
    level: {
      es: "Nv. 27",
      en: "Lv. 27",
    },
    requires: {
      es: ["Yelmos"],
      en: ["Helmets"],
    },
    details: {
      es: [
        "+1 a Todos los Niveles de Habilidad",
        "+10 de Energía",
        "+2 al mana Tras Cada Muerte",
        "Resistencia a los Rayos +30%",
        "Daño Reducido en 7",
        "+2 al Radio de Luz",
      ],
      en: [
        "+1 To All Skill Levels",
        "+10 To Energy",
        "+2 To Mana After Each Kill",
        "Lightning Resist +30%",
        "Damage Reduced By 7",
        "+2 To Light Radius",
      ],
    },
    expansion: "lod",
    references: {
      es: "https://diablo.fandom.com/wiki/Lore_Rune_Word",
      en: "https://diablo.fandom.com/wiki/Lore_Rune_Word",
    },
  },
  holy_thunder: {
    key: "holy_thunder",
    runes: ["eth", "ral", "ort", "tal"],
    name: {
      es: "Trueno Sagrado",
      en: "Holy Thunder",
    },
    level: {
      es: "Nv. 21",
      en: "Lv. 21",
    },
    requires: {
      es: ["Cetros"],
      en: ["Scepters"],
    },
    details: {
      es: [
        "+60% Daño Mejorado",
        "5% Resistencia Máxima a los Rayos",
        "+75 Daño de Veneno Durante 5 Segundos",
        "Añade 5-30 Daño de Fuego",
        "Añade 21-110 Daño de Relámpago",
        "+10 al Daño Máximo",
        "-25% a la Defensa del Objetivo",
        "Resistencia a los Rayos +60%",
        "+3 para Golpe Sagrado (Solo Paladín)",
        "Nivel 7 Cadena de Rayos (60 Cargas)",
      ],
      en: [
        "+60% Enhanced Damage",
        "-25% Target Defense",
        "5-30 Fire Damage",
        "21-110 Lightning Damage",
        "+75 Poison Damage for 5 seconds",
        "+10 to Maximum Damage",
        "+60% Lightning Resist",
        "+5 to Maximum Lightning Resist",
        "+3 to Holy Shock (Paladin only)",
        "Level 7 Chain Lightning (60 charges)",
      ],
    },
    expansion: "lod",
    references: {
      es: "https://diablo.fandom.com/wiki/Holy_Thunder_Rune_Word",
      en: "https://diablo.fandom.com/wiki/Holy_Thunder_Rune_Word",
    },
  },
  crescent_moon: {
    key: "crescent_moon",
    runes: ["shael", "um", "tir"],
    name: {
      es: "Luna Creciente",
      en: "Crescent Moon",
    },
    level: {
      es: "Nv. 47",
      en: "Lv. 47",
    },
    requires: {
      es: ["Armas de Asta", "Hachas", "Espadas"],
      en: ["Polearms", "Axes", "Swords"],
    },
    details: {
      es: [
        "10% Posibilidad de Lanzar el Nivel 17 Cadena de Rayos al Azotar",
        "7% Posibilidad de Lanzar el Nivel 13 Campo Estático al Azotar",
        "+20% Velocidad de Ataque Aumentada",
        "+180-220% Daño Mejorado (varía)",
        "Ignorar Defensa del Objetivo",
        "-35% a la Resistencia al Relámpago del Enemigo",
        "25% Posibilidad de Heridas Abiertas",
        "+9-11 Absorción de Magia (varía)",
        "+2 de maná tras cada muerte",
        "Nivel 18 Invoca al Lobo del Espíritu (30 cargas)",
      ],
      en: [
        "10% Chance To Cast Level 17 Chain Lightning On Striking",
        "7% Chance To Cast Level 13 Static Field On Striking",
        "+20% Increased Attack Speed",
        "+180-220% Enhanced Damage",
        "Ignore Target's Defense",
        "-35% To Enemy Lightning Resist",
        "+25% Chance of Open Wounds",
        "+9-11 Magic Absorb",
        "+2 To Mana After Each Kill",
        "Level 18 Summon Spirit Wolf (30 Charges)",
      ],
    },
    expansion: "lod",
    references: {
      es: "https://diablo.fandom.com/wiki/Crescent_Moon_Rune_Word",
      en: "https://diablo.fandom.com/wiki/Crescent_Moon_Rune_Word",
    },
  },
  wind: {
    key: "wind",
    runes: ["sur", "el"],
    name: {
      es: "Viento",
      en: "Wind",
    },
    level: {
      es: "Nv. 61",
      en: "Lv. 61",
    },
    requires: {
      es: ["Armas Melee"],
      en: ["Melee Weapons"],
    },
    details: {
      es: [
        "10% Posibilidad de Lanzar el Nivel 9 Tornado al Azotar",
        "+20% Correr/Andar Mas Rápido",
        "+40% Velocidad de Ataque Aumentada",
        "+15% Recuperación de Impacto Mas Rápida",
        "+120-160% Daño Mejorado (varia)",
        "-50% Defensa del Objetivo",
        "+50 de Puntuación de Ataque",
        "El Impacto Ciega al Objetivo",
        "+1 al Radio de Luz",
        "Nivel 13 Vendaval (127 Cargas)",
      ],
      en: [
        "10% Chance To Cast Level 9 Tornado On Striking",
        "+20% Faster Run/Walk",
        "+40% Increased Attack Speed",
        "+15% Faster Hit Recovery",
        "+120-160% Enhanced Damage",
        "-50% Target Defense",
        "+50 To Attack Rating",
        "Hit Blinds Target",
        "+1 To Light Radius",
        "Level 13 Twister (127 Charges)",
      ],
    },
    expansion: "lod",
    references: {
      es: "https://diablo.fandom.com/wiki/Wind_Rune_Word",
      en: "https://diablo.fandom.com/wiki/Wind_Rune_Word",
    },
  },
  metamorphosis: {
    key: "metamorphosis",
    runes: ["io", "cham", "fal"],
    name: {
      es: "Metamorfosis",
      en: "Metamorphosis",
    },
    level: {
      es: "Nv. 67",
      en: "Lv. 67",
    },
    requires: {
      es: ["Yelmos"],
      en: ["Helmets"],
    },
    details: {
      es: [
        {
          "Marca del lobo": [
            "Los ataques de Hombre lobo otorgan una marca durante 180 seg.",
            "+30% de bonus al índice de ataque",
            "Aumenta la vida máxima un 40 %",
          ],
        },
        {
          "Marca del oso": [
            "Los ataques de Hombre oso otorga una marca durante 180 seg.",
            "+25% de velocidad de ataque",
            "Daño físico sufrido reducido un 20%",
          ],
        },
        "+5 p. a las habilidades de cambio de forma (solo druida)",
        "+25% de probabilidad de ataque aplastante",
        "+50-80% de defensa mejorada (varia)",
        "+10 p. de fuerza",
        "+10 p. de vitalidad",
        "+10 p. a todas las resistencias",
        "No te pueden congelar",
      ],
      en: [
        {
          "Mark of the Wolf": [
            "Werewolf strikes grant Mark for 180 seconds",
            "+30% Bonus to Attack Rating",
            "Increase Maximum Life 40%",
          ],
        },
        {
          "Mark of the Bear": [
            "Werebear strikes grant Mark for 180 seconds",
            "+25% Attack Speed",
            "Physical Damage Received Reduced by 20%",
          ],
        },
        "+5 to Shape Shifting Skills (Druid only)",
        "+25% Chance of Crushing Blow",
        "+50-80% Enhanced Defense",
        "+10 to Strength",
        "+10 to Vitality",
        "All Resistances +10",
        "Cannot be Frozen",
      ],
    },
    expansion: "lod",
    references: {
      es: "https://diablo2.io/runewords/metamorphosis-t1282120.html",
      en: "https://diablo2.io/runewords/metamorphosis-t1282120.html",
    },
  },
  splendor: {
    key: "splendor",
    runes: ["eth", "lum"],
    name: {
      es: "Esplendor",
      en: "Splendor",
    },
    level: {
      es: "Nv. 37",
      en: "Lv. 37",
    },
    requires: {
      es: ["Escudos"],
      en: ["Shields"],
    },
    details: {
      es: [
        "+1 a Todas las Habilidades",
        "+10% Velocidad de Lanzamiento Mayor",
        "+20% Velocidad de Bloqueo Mayor",
        "+60-100% Defensa Perfeccionada (varia)",
        "+10 de Energía",
        "Regenerar mana 15%",
        "+50% Oro Extra de los Monstruos",
        "+20% de Probabilidad de Encontrar Objetos Mágicos",
        "+3 al Radio de Luz",
      ],
      en: [
        "+1 To All Skills",
        "+10% Faster Cast Rate",
        "+20% Faster Block Rate",
        "+60-100% Enhanced Defense",
        "+10 To Energy",
        "Regenerate Mana 15%",
        "50% Extra Gold From Monsters",
        "20% Better Chance of Getting Magic Items",
        "+3 To Light Radius",
      ],
    },
    expansion: "lod",
    references: {
      es: "https://diablo.fandom.com/wiki/Splendor_Rune_Word",
      en: "https://diablo.fandom.com/wiki/Splendor_Rune_Word",
    },
  },
  doom: {
    key: "doom",
    runes: ["hel", "ohm", "um", "lo", "cham"],
    name: {
      es: "Fatalidad",
      en: "Doom",
    },
    level: {
      es: "Nv. 67",
      en: "Lv. 67",
    },
    requires: {
      es: ["Armas de Asta", "Hachas", "Martillos"],
      en: ["Polearms", "Axes", "Hammers"],
    },
    details: {
      es: [
        "5% Posibilidad de Lanzar el Nivel 18 Volcán al Azotar",
        "Nivel 12 Aura Congelación Sagrada Cuando está Equipado",
        "+2 a Todas las Habilidades",
        "+45% Velocidad de Ataque Aumentada",
        "+330-370% Daño Mejorado (varía)",
        "-(40-60)% a la Resistencia al Frío del Enemigo",
        "20% Azote Mortal",
        "25% Posibilidad de Heridas Abiertas",
        "Evita la Curación del Monstruo",
        "Congela al Objetivo",
        "Requisitos -20%",
      ],
      en: [
        "5% Chance To Cast Level 18 Volcano On Striking",
        "Level 12 Holy Freeze Aura When Equipped",
        "+2 To All Skills",
        "+45% Increased Attack Speed",
        "+330-370% Enhanced Damage",
        "-(40-60)% To Enemy Cold Resist",
        "+20% Deadly Strike",
        "+25% Chance of Open Wounds",
        "Prevent Monster Heal",
        "Freezes Target +3",
        "Requirements -20%",
      ],
    },
    expansion: "lod",
    references: {
      es: "https://diablo.fandom.com/wiki/Doom_Rune_Word",
      en: "https://diablo.fandom.com/wiki/Doom_Rune_Word",
    },
  },
  rhyme: {
    key: "rhyme",
    runes: ["shael", "eth"],
    name: {
      es: "Rima",
      en: "Rhyme",
    },
    level: {
      es: "Nv. 29",
      en: "Lv. 29",
    },
    requires: {
      es: ["Escudos"],
      en: ["Shields"],
    },
    details: {
      es: [
        "Velocidad de Bloqueo un +40% más Rápido",
        "+20% de Probabilidad de Bloqueo",
        "15% de Regeneración de Maná",
        "+25 a Todas las Resistencias",
        "No Te Pueden Congelar",
        "+50% de Oro Extra de los Monstruos",
        "+25% de Probabilidad de Encontrar Objetos Mágicos",
      ],
      en: [
        "20% Increased Chance of Blocking",
        "40% Faster Block Rate",
        "+25 to All Resistances",
        "Regenerate Mana 15%",
        "Cannot Be Frozen",
        "50% Extra Gold From Monsters",
        "25% Better Chance Of Getting Magic Items",
      ],
    },
    expansion: "lod",
    references: {
      es: "https://diablo.fandom.com/wiki/Rhyme_Rune_Word",
      en: "https://diablo.fandom.com/wiki/Rhyme_Rune_Word",
    },
  },
  void: {
    key: "void",
    runes: ["thul", "zod", "ist"],
    name: {
      es: "Vacio",
      en: "Void",
    },
    level: {
      es: "Nv. 69",
      en: "Lv. 69",
    },
    requires: {
      es: ["Dagas"],
      en: ["Daggers"],
    },
    details: {
      es: [
        "+2 a todas las habilidades",
        "+40% de velocidad de lanzamiento mayor",
        "+10-15% al daño de habilidad mágica (varia)",
        "+1 a Abismo (Nivel 3)",
        "+8-12 a todos los atributos (varia)",
        "Nivel 4 de Decrepitud (35/35 cargas)",
        "Añade 3-14 de daño por frío (varia)",
        "Indestructible",
      ],
      en: [
        "+2 to All Skills",
        "+40% Faster Cast Rate",
        "+10-15% to Magic Skill Damage",
        "+1-3 to Abyss",
        "+8-12 to all Attributes",
        "Level 4 Decrepify (35/35 Charges)",
        "Adds 3-14 Cold Damage",
        "Indestructible",
        "30% Better Chance of Getting Magic Items",
      ],
    },
    expansion: "row",
    references: {
      es: "https://diablo2.io/runewords/void-t1673936.html",
      en: "https://diablo2.io/runewords/void-t1673936.html",
    },
  },
  rift: {
    key: "rift",
    runes: ["hel", "ko", "lem", "gul"],
    name: {
      es: "Grieta",
      en: "Rift",
    },
    level: {
      es: "Nv. 53",
      en: "Lv. 53",
    },
    requires: {
      es: ["Armas de Asta", "Cetros"],
      en: ["Polearms", "Scepters"],
    },
    details: {
      es: [
        "20% de Posibilidades de Lanzar el Nivel 16 Tornado al Azotar",
        "16% de Posibilidades de Lanzar el Nivel 21 Orbe Helado al Atacar",
        "20% de Bonificación en el Ataque",
        "Añade 160-250 de Daño Mágico",
        "Añade 60-180 de Daño de Fuego",
        "+5-10 a Todos los Atributos (varia)",
        "+10 de Destreza",
        "38% el Daño Infligido Repercute en el Mana",
        "75% Oro Extra de los Monstruos",
        "Nivel 15 de Doncella de Hierro (40 Cargas)",
        "Requisitos -20%",
      ],
      en: [
        "20% Chance To Cast Level 16 Tornado On Striking",
        "16% Chance To Cast Level 21 Frozen Orb On Attack",
        "20% Bonus To Attack Rating",
        "Adds 160-250 Magic Damage",
        "Adds 60-180 Fire Damage",
        "+5-10 To All Stats (varies)",
        "+10 To Dexterity",
        "38% Damage Taken Goes To Mana",
        "75% Extra Gold From Monsters",
        "Level 15 Iron Maiden (40 Charges)",
        "Requirements -20%",
      ],
    },
    expansion: "lod",
    references: {
      es: "https://diablo.fandom.com/wiki/Rift_Rune_Word",
      en: "https://diablo.fandom.com/wiki/Rift_Rune_Word",
    },
  },
  flickering_flame: {
    key: "flickering_flame",
    runes: ["nef", "pul", "vex"],
    name: {
      es: "Llama Trémula",
      en: "Flickering Flame",
    },
    level: {
      es: "Nv. 55",
      en: "Lv. 55",
    },
    requires: {
      es: ["Yelmos"],
      en: ["Helmets"],
    },
    details: {
      es: [
        "Aura Resistencia al fuego de nivel 4-8 si está equipado (varia)",
        "+3 p. a las habilidades de fuego",
        "-10-15% de resistencia enemiga al fuego (varia)",
        "+30% de defensa mejorada",
        "+30 p. de defensa contra misiles",
        "+50-75 p. de maná (varia)",
        "La congelación dura la mitad",
        "+5% de resistencia máxima al fuego",
        "Duración del veneno reducida un 50%",
      ],
      en: [
        "Level 4-8 Resist Fire Aura When Equipped",
        "+3 To Fire Skills",
        "-10-15% to Enemy Fire Resist",
        "+30% Enhanced Defense",
        "+30 Defense vs. Missile",
        "+50-75 To Mana",
        "Half Freeze Duration",
        "+5% To Maximum Fire Resist",
        "Poison Length Reduced by 50%",
      ],
    },
    expansion: "lod",
    references: {
      es: "https://diablo.fandom.com/wiki/Flickering_Flame_Rune_Word",
      en: "https://diablo.fandom.com/wiki/Flickering_Flame_Rune_Word",
    },
  },
  white: {
    key: "white",
    runes: ["dol", "io"],
    name: {
      es: "Blancura",
      en: "White",
    },
    level: {
      es: "Nv. 35",
      en: "Lv. 35",
    },
    requires: {
      es: ["Varas"],
      en: ["Wands"],
    },
    details: {
      es: [
        "El Impacto Hace que el Monstruo Huya 25%",
        "+10 Vitalidad",
        "+3 Para las Habilidades de Veneno y Hueso (Solo Nigromante)",
        "+3 Para Armadura de Huesos (Solo Nigromante)",
        "+2 Para Lanza Osea (Solo Nigromante)",
        "+4 Para Dominio de los Esqueletos (Solo Nigromante)",
        "Daño de Magia Reducido en 4",
        "20% Velocidad de Lanzamiento Mayor",
        "+13 de Mana",
      ],
      en: [
        "Hit Causes Monster To Flee +25%",
        "+10 To Vitality",
        "+3 To Poison and Bone Spells (Necromancer Only)",
        "+3 To Bone Armor (Necromancer Only)",
        "+2 To Bone Spear (Necromancer Only)",
        "+4 To Skeleton Mastery (Necromancer Only)",
        "Magic Damage Reduced By 4",
        "20% Faster Cast Rate",
        "+13 To Mana",
      ],
    },
    expansion: "lod",
    references: {
      es: "https://diablo.fandom.com/wiki/White_Rune_Word",
      en: "https://diablo.fandom.com/wiki/White_Rune_Word",
    },
  },
  insight: {
    key: "insight",
    runes: ["ral", "tir", "tal", "sol"],
    name: {
      es: "Perspicacia",
      en: "Insight",
    },
    level: {
      es: "Nv. 27",
      en: "Lv. 27",
    },
    requires: {
      es: ["Armas de Asta", "Bastones", "Arcos", "Balletas"],
      en: ["Polearms", "Staves", "Bows", "Crossbows"],
    },
    details: {
      es: [
        "Aura Meditación de Nivel 12-17 si está Equipado (varia)",
        "Velocidad de Lanzamiento un +35% más Rápido",
        "+200-260% de Daño Mejorado (varia)",
        "+9 p. de Daño Mínimo",
        "+180-250% de Bonus al Índice de Ataque (varia)",
        "Añade 5-30 p. de Daño de Fuego",
        "+75 p. de Daño de Veneno Durante 5 s",
        "+1-6 a Azote Crítico (varia)",
        "+5 a Todos los Atributos",
        "+2 p. de Maná tras Cada Asesinato",
        "+23% de Probabilidad de Encontrar Objetos Mágicos",
      ],
      en: [
        "Level 12-17 Meditation Aura When Equipped",
        "+35% Faster Cast Rate",
        "+200-260% Enhanced Damage (varies)",
        "+9 To Minimum Damage",
        "180-250% Bonus to Attack Rating",
        "Adds 5-30 Fire Damage",
        "+75 Poison Damage Over 5 Seconds",
        "+1-6 To Critical Strike",
        "+5 To All Attributes",
        "+2 To Mana After Each Kill",
        "23% Better Chance of Getting Magic Items",
      ],
    },
    expansion: "lod",
    references: {
      es: "https://diablo.fandom.com/wiki/Insight_Rune_Word",
      en: "https://diablo.fandom.com/wiki/Insight_Rune_Word",
    },
  },
  chaos: {
    key: "chaos",
    runes: ["fal", "ohm", "um"],
    name: {
      es: "Caos",
      en: "Chaos",
    },
    level: {
      es: "Nv. 57",
      en: "Lv. 57",
    },
    requires: {
      es: ["Garras"],
      en: ["Katars"],
    },
    details: {
      es: [
        "9% Posibilidad de Lanzar el Nivel 11 Orbe Helado al Azotar",
        "11% Posibilidad de Lanzar el Nivel 9 Descarga de Energía al Azotar",
        "+35% Velocidad de Ataque Aumentada",
        "+290-328% Daño Mejorado (varia)",
        "Añade 216-471 Daño Mágico",
        "25% Posibilidad de Heridas Abiertas",
        "+1 para Torbellino",
        "+10 de Fuerza",
        "+15 Vida Tras Cada Demonio Muerto",
      ],
      en: [
        "9% Chance To Cast Level 11 Frozen Orb On Striking",
        "11% Chance To Cast Level 9 Charged Bolt On Striking",
        "+35% Increased Attack Speed",
        "+290-340% Enhanced Damage",
        "Adds 216-471 Magic Damage",
        "+25% Chance of Open Wounds",
        "+1 To Whirlwind",
        "+10 To Strength",
        "+15 Life After Each Demon Kill",
      ],
    },
    expansion: "lod",
    references: {
      es: "https://diablo.fandom.com/wiki/Chaos_Rune_Word",
      en: "https://diablo.fandom.com/wiki/Chaos_Rune_Word",
    },
  },
  voice_of_reason: {
    key: "voice_of_reason",
    runes: ["lem", "ko", "el", "eld"],
    name: {
      es: "Voz de la Razón",
      en: "Voice of Reason",
    },
    level: {
      es: "Nv. 43",
      en: "Lv. 43",
    },
    requires: {
      es: ["Mazas", "Espadas"],
      en: ["Maces", "Swords"],
    },
    details: {
      es: [
        "15% de Posibilidades de Lanzar el Nivel 13 Orbe Helado al Azotar",
        "18% de Posibilidades de Lanzar el Nivel 20 Explosión de Hielo al Azotar",
        "+50 de Puntuación de Ataque",
        "+220-350% Daño a los Demonios (varia)",
        "+355-375% Daño a los Muertos Vivientes (varia)",
        "+50 a la Puntuación de Ataque contra Muertos Vivientes",
        "Añade 100-220 de Daño de Frio",
        "-24% para Resistencia al Frio Enemigo",
        "+10 de Destreza",
        "No Puede Congelarse",
        "75% Oro Extra de los Monstruos",
        "+1 al Radio de Luz",
      ],
      en: [
        "15% Chance To Cast Level 13 Frozen Orb On Striking",
        "18% Chance To Cast Level 20 Ice Blast On Striking",
        "+50 To Attack Rating",
        "+220-350% Damage To Demons",
        "+355-375% Damage To Undead",
        "+50 To Attack Rating Against Undead",
        "Adds 100-220 Cold Damage",
        "-24% To Enemy Cold Resistance",
        "+10 To Dexterity",
        "Cannot Be Frozen",
        "75% Extra Gold From Monsters",
        "+1 To Light Radius",
      ],
    },
    expansion: "lod",
    references: {
      es: "https://diablo.fandom.com/wiki/Voice_of_Reason_Rune_Word",
      en: "https://diablo.fandom.com/wiki/Voice_of_Reason_Rune_Word",
    },
  },
  duress: {
    key: "duress",
    runes: ["shael", "um", "thul"],
    name: {
      es: "Coaccion",
      en: "Duress",
    },
    level: {
      en: "Nv. 47",
      es: "Lv. 47",
    },
    requires: {
      es: ["Armaduras"],
      en: ["Armors"],
    },
    details: {
      es: [
        "+40% Recuperación de Impacto Mas Rápida",
        "+10-20% Daño Mejorado",
        "Añade 37-133 Daño de Frio (Duración 2 Segundos)",
        "15% Posibilidad de Golpe Triturador",
        "33% Posibilidad de Heridas Abiertas",
        "+150-200% Defensa Perfeccionada (varia)",
        "20% Drenaje de Resistencia mas lento",
        "Resistencia al Frio +45%",
        "Resistencia al Rayo +15%",
        "Resistencia al Fuego +15%",
        "Resistencia al Veneno +15%",
      ],
      en: [
        "+40% Faster Hit Recovery",
        "+10-20% Enhanced Damage",
        "Adds 37-133 Cold Damage 2 sec. Duration (Normal)",
        "15% Chance of Crushing Blow",
        "33% Chance of Open Wounds",
        "+150-200% Enhanced Defense",
        "-20% Slower Stamina Drain",
        "Cold Resist +45%",
        "Lightning Resist +15%",
        "Fire Resist +15%",
        "Poison Resist +15%",
      ],
    },
    expansion: "lod",
    references: {
      es: "https://diablo.fandom.com/wiki/Duress_Rune_Word",
      en: "https://diablo.fandom.com/wiki/Duress_Rune_Word",
    },
  },
  smoke: {
    key: "smoke",
    runes: ["nef", "lum"],
    name: {
      es: "Humo",
      en: "Smoke",
    },
    level: {
      es: "Nv. 37",
      en: "Lv. 37",
    },
    requires: {
      es: ["Armaduras"],
      en: ["Armors"],
    },
    details: {
      es: [
        "+75% Defensa Perfeccionada",
        "Todas las Resistencias +50%",
        "+280 Defensa Contra Misil",
        "20% Recuperación de Impacto Mas Rápida",
        "Nivel 6 Debilitar (18 Cargas)",
        "+10 de Energía",
        "-1 al Radio de Luz",
      ],
      en: [
        "+75% Enhanced Defense",
        "+280 Defense vs. Missiles",
        "All Resistances +50",
        "20% Faster Hit Recovery",
        "Level 6 Weaken (18 Charges)",
        "+10 To Energy",
        "-1 To Light Radius",
      ],
    },
    expansion: "lod",
    references: {
      es: "https://diablo.fandom.com/wiki/Smoke_Rune_Word",
      en: "https://diablo.fandom.com/wiki/Smoke_Rune_Word",
    },
  },
  obsession: {
    key: "obsession",
    runes: ["zod", "ist", "lem", "lum", "io", "nef"],
    name: {
      es: "Obsesión",
      en: "Obsession",
    },
    level: {
      es: "Nv. 69",
      en: "Lv. 69",
    },
    requires: {
      es: ["Bastones"],
      en: ["Staves"],
    },
    details: {
      es: [
        "Indestructible",
        "24% de probabilidad de lanzar Debilitar de nivel 10 al recibir un golpe",
        "+4 p. a todas las habilidades",
        "+65% de velocidad de lanzamiento",
        "Recuperación de golpe un 60% más rápida",
        "Repele al objetivo",
        "+10 p. de vitalidad",
        "+10 p. de energía",
        "Aumenta la vida máxima un 15-25% (varia)",
        "15-30% de regeneración de maná (varia)",
        "+60-70 p. a todas las resistencias (varia)",
        "75% de oro extra de los monstruos",
        "+30% de probabilidad de encontrar objetos mágicos",
      ],
      en: [
        "Indestructible",
        "24% Chance to cast level 10 Weaken when struck",
        "+4 To All Skills",
        "+65% Faster Cast Rate",
        "+60% Faster Hit Recovery",
        "Knockback",
        "+10 To Vitality",
        "+10 To Energy",
        "Increase Maximum Life 15-25% (varies)",
        "Regenerate Mana 15-30% (varies)",
        "All Resistances +60-70 (varies)",
        "75% Extra Gold from Monsters",
        "30% Better Chance of Getting Magic Items",
      ],
    },
    expansion: "lod",
    references: {
      es: "https://diablo.fandom.com/wiki/Obsession_Rune_Word",
      en: "https://diablo.fandom.com/wiki/Obsession_Rune_Word",
    },
  },
  fury: {
    key: "fury",
    runes: ["jah", "gul", "eth"],
    name: {
      es: "Furia",
      en: "Fury",
    },
    level: {
      es: "Nv. 65",
      en: "Lv. 65",
    },
    requires: {
      es: ["Armas Melee"],
      en: ["Melee Weapons"],
    },
    details: {
      es: [
        "+40% Velocidad de Ataque Aumentada",
        "+209% Daño Mejorado",
        "Ignorar Defensa del Objetivo",
        "-25% Defensa del Objetivo",
        "20% de Bonificación en el Ataque",
        "6% Vida Robada por Impacto",
        "33% Azote Mortal",
        "66% Posibilidad de Heridas Abiertas",
        "Evita la Curación del Monstruo",
        "+5 Para Frenesí (solo Bárbaro)",
      ],
      en: [
        "+209% Enhanced Damage",
        "40% Increased Attack Speed",
        "Prevent Monster Heal",
        "66% Chance of Open Wounds",
        "33% Chance of Deadly Strike",
        "-25% Target Defense",
        "20% to Attack Rating",
        "6% Life Stolen Per Hit",
        "Ignores Target Defense",
        "+5 to Frenzy (Barbarian only)",
      ],
    },
    expansion: "lod",
    references: {
      es: "https://diablo.fandom.com/wiki/Fury_Rune_Word",
      en: "https://diablo.fandom.com/wiki/Fury_Rune_Word",
    },
  },
  beast: {
    key: "beast",
    runes: ["ber", "tir", "um", "mal", "lum"],
    name: {
      es: "Bestia",
      en: "Beast",
    },
    level: {
      es: "Nv. 63",
      en: "Lv. 63",
    },
    requires: {
      es: ["Martillos", "Cetros", "Hachas"],
      en: ["Hammers", "Scepters", "Axes"],
    },
    details: {
      es: [
        "Nivel 9 Aura Fanatismo Cuando esta Equipado",
        "+40% Velocidad de Ataque aumentada",
        "+240-270% Daño Mejorado (varia)",
        "20% Posibilidad de Golpe Triturador",
        "25% Posibilidad de Heridas Abiertas",
        "+3 a Hombre Oso",
        "+3 a Licantropía",
        "Evita la Curación del Monstruo",
        "+25-40 de Fuerza (varia)",
        "+10 de Energía",
        "+2 mana Tras Cada Muerte",
        "Nivel 13 Invoca al Oso Pardo (5 Cargas)",
      ],
      en: [
        "Level 9 Fanaticism Aura When Equipped",
        "+40% Increased Attack Speed",
        "+240-270% Enhanced Damage",
        "+20% Chance of Crushing Blow",
        "+25% Chance of Open Wounds",
        "+3 To Werebear",
        "+3 To Lycanthropy",
        "Prevent Monster Heal",
        "+25-40 To Strength",
        "+10 To Energy",
        "+2 To Mana After Each Kill",
        "Level 13 Summon Grizzly (5 Charges)",
      ],
    },
    expansion: "lod",
    references: {
      es: "https://diablo.fandom.com/wiki/Beast_Rune_Word",
      en: "https://diablo.fandom.com/wiki/Beast_Rune_Word",
    },
  },
  vigilance: {
    key: "vigilance",
    runes: ["dol", "gul"],
    name: {
      es: "Vigilancia",
      en: "Vigilance",
    },
    level: {
      es: "Nv. 53",
      en: "Lv. 53",
    },
    requires: {
      es: ["Escudos"],
      en: ["Shields"],
    },
    details: {
      es: [
        "5% de probabilidad de lanzar el nivel 10 de Anillo de fuego al recibir un azote",
        "+10% de velocidad de correr/andar mayor",
        "+30% de velocidad de bloqueo mayor",
        "+20-40 a la vida (varia)",
        "+20-40 al maná (varia)",
        "Todas las resistencias +25-35 (varia)",
        "+75-100% de defensa aumentada (varia)",
        "Reponer vida +7",
        "+5% a la resistencia máxima al veneno",
      ],
      en: [
        "5% Chance to cast level 10 Ring of Fire when struck",
        "+10% Faster Run/Walk",
        "+30% Faster Block Rate",
        "+20-40 to Life",
        "+20-40 to Mana",
        "All Resistances +25-35",
        "+75-100% Enhanced Defense",
        "Replenish Life +7",
        "+5% to Maximum Poison Resist",
      ],
    },
    expansion: "row",
    references: {
      es: "https://diablo2.io/runewords/vigilance-t1673937.html",
      en: "https://diablo2.io/runewords/vigilance-t1673937.html",
    },
  },
  honor: {
    key: "honor",
    runes: ["amn", "el", "ith", "tir", "sol"],
    name: {
      es: "Honor",
      en: "Honor",
    },
    level: {
      es: "Nv. 27",
      en: "Lv. 27",
    },
    requires: {
      es: ["Armas Melee"],
      en: ["Melee Weapons"],
    },
    details: {
      es: [
        "+160% Daño Mejorado",
        "+9 al Daño Mínimo",
        "+9 al Daño Máximo",
        "25% Azote Mortal",
        "+250 de Puntuación de Ataque",
        "+1 a Todos los Niveles de Habilidad",
        "7% Vida Robada por Impacto",
        "Repostar Vida +10",
        "+10 Fuerza",
        "+1 al Radio de Luz",
        "+2 al mana Tras Cada Muerte",
      ],
      en: [
        "+160% Enhanced Damage",
        "+9 to Minimum Damage",
        "+9 to Maximum Damage",
        "+25% Deadly Strike",
        "+250 to Attack Rating",
        "+1 to All Skills",
        "7% Life Stolen per Hit",
        "+10 Replenish Life",
        "+10 to Strength",
        "+1 to Light Radius",
        "+2 to Mana per Kill",
      ],
    },
    expansion: "lod",
    references: {
      es: "https://diablo.fandom.com/wiki/Honor_Rune_Word",
      en: "https://diablo.fandom.com/wiki/Honor_Rune_Word",
    },
  },
  cure: {
    key: "cure",
    runes: ["shael", "io", "tal"],
    name: {
      es: "Cura",
      en: "Cure",
    },
    level: {
      es: "Nv. 35",
      en: "Lv. 35",
    },
    requires: {
      es: ["Yelmos"],
      en: ["Helmets"],
    },
    details: {
      es: [
        "Aura Purificación de nivel 1 si está equipado",
        "Recuperación de golpe un +20 % más rápida",
        "+75-100 % de defensa mejorada",
        "+10 p. de vitalidad",
        "Aumenta la vida máxima un 5%",
        "+40-60 % de resistencia al veneno",
        "Duración del veneno reducida un 50%",
      ],
      en: [
        "+20% Faster Hit Recovery",
        "+10 to Vitality",
        "Poison Resist +30%",
        "Level 1 Cleansing Aura when Equipped",
        "+75-100% Enhanced Defense",
        "Increase Maximum Life 5%",
        "Poison Resist +10-30% (+40-60% total)",
        "Poison Length Reduced by 50%",
      ],
    },
    expansion: "lod",
    references: {
      es: "https://diablo.fandom.com/wiki/Cure_Rune_Word",
      en: "https://diablo.fandom.com/wiki/Cure_Rune_Word",
    },
  },
  enigma: {
    key: "enigma",
    runes: ["jah", "ith", "ber"],
    name: {
      es: "Enigma",
      en: "Enigma",
    },
    level: {
      es: "Nv. 65",
      en: "Lv. 65",
    },
    requires: {
      es: ["Armaduras"],
      en: ["Armors"],
    },
    details: {
      es: [
        "+2 a Todas las Habilidades",
        "+45% Correr/Andar Mas Rápido",
        "+1 para Teletransporte",
        "+750-775 Defensa (varia)",
        "+0-74 de Fuerza (0.75 por Nivel)",
        "Aumenta la Vida Máxima 5%",
        "Daño Reducido en 8%",
        "+14 Vida Tras Cada Muerte",
        "15% Daño Infligido Repercute en el mana",
        "+1-99% de Probabilidad de Encontrar Objetos Mágicos [1 por Nivel]",
      ],
      en: [
        "+2 To All Skills",
        "+45% Faster Run/Walk",
        "+1 To Teleport",
        "+750-775 Defense",
        "+0-74 To Strength (Based On Character Level)",
        "Increase Maximum Life 5%",
        "Physical Damage Received Reduced By 8%",
        "+14 Life After Each Kill",
        "15% Damage Taken Goes To Mana",
        "+1-99% Better Chance of Getting Magic Items (Based On Character Level)",
      ],
    },
    expansion: "lod",
    references: {
      es: "https://diablo.fandom.com/wiki/Enigma_Rune_Word",
      en: "https://diablo.fandom.com/wiki/Enigma_Rune_Word",
    },
  },
  stone: {
    key: "stone",
    runes: ["shael", "um", "pul", "lum"],
    name: {
      es: "Roca",
      en: "Stone",
    },
    level: {
      es: "Nv. 47",
      en: "Lv. 47",
    },
    requires: {
      es: ["Armaduras"],
      en: ["Armors"],
    },
    details: {
      es: [
        "+60% Recuperación de Impacto Mas Rápida",
        "+250-290% Defensa Mejorada (varia)",
        "+300 Defensa contra Misiles",
        "+16 de Fuerza",
        "+16 de Vitalidad",
        "+10 de Energía",
        "Todas las Resistencias +15",
        "Nivel 16 Roca Ígnea (80 Cargas)",
        "Nivel 16 Golem de Arcilla (16 Cargas)",
      ],
      en: [
        "+60% Faster Hit Recovery",
        "+250-290% Enhanced Defense",
        "+300 Defense vs. Missile",
        "+16 To Strength",
        "+16 To Vitality",
        "+10 To Energy",
        "All Resistances +15",
        "Level 16 Molten Boulder (80 Charges)",
        "Level 16 Clay Golem (16 Charges)",
      ],
    },
    expansion: "lod",
    references: {
      es: "https://diablo.fandom.com/wiki/Stone_Rune_Word",
      en: "https://diablo.fandom.com/wiki/Stone_Rune_Word",
    },
  },
  coven: {
    key: "coven",
    runes: ["ist", "ral", "io"],
    name: {
      es: "Aquelarre",
      en: "Coven",
    },
    level: {
      es: "Nv. 51",
      en: "Lv. 51",
    },
    requires: {
      es: ["Yelmos"],
      en: ["Helmets"],
    },
    details: {
      es: [
        "5% de probabilidad de lanzar Sigilo: Letargo de nivel 10 al recibir un golpe",
        "+1 a todas las habilidades",
        "+20% de velocidad de lanzamiento mayor",
        "+30-50% de defensa aumentada (varia)",
        "+10 a la vitalidad",
        "Resistencia al fuego +30%",
        "+1-5 de vida después de cada muerte (varia)",
        "+26-40% de probabilidad de encontrar objetos mágicos (varia)",
      ],
      en: [
        "5% Chance to cast level 10 Sigil Lethargy when struck",
        "+1 to All Skills",
        "+20% Faster Cast Rate",
        "+30-50% Enhanced Defense",
        "+1-5 Life after each Kill",
        "26-40% Better Chance of Getting Magic Items",
        "Fire Resist +30%",
        "+10 to Vitality",
      ],
    },
    expansion: "row",
    references: {
      es: "https://diablo2.io/runewords/coven-t1673935.html",
      en: "https://diablo2.io/runewords/coven-t1673935.html",
    },
  },
  silence: {
    key: "silence",
    runes: ["dol", "eld", "hel", "ist", "tir", "vex"],
    name: {
      es: "Silencio",
      en: "Silence",
    },
    level: {
      es: "Nv. 55",
      en: "Lv. 55",
    },
    requires: {
      es: ["Armas"],
      en: ["Weapons"],
    },
    details: {
      es: [
        "+2 a Todos los Niveles de Habilidad",
        "20% Velocidad de Ataque Aumentada",
        "20% Recuperación de Impacto Mas Rápida",
        "+200% Daño Mejorado",
        "+75% Daño a los Muertos Vivientes",
        "+50 de Puntuación de Ataque Contra Muertos Vivientes",
        "11% mana Robado por Impacto",
        "El Impacto Ciega al Objetivo +33",
        "El Impacto Hace que el Monstruo Huya 25%",
        "Todas las Resistencias +75%",
        "+2 al mana Tras Cada Muerte",
        "+30% de Probabilidad de Encontrar Objetos Mágicos",
        "Requisitos -20%",
      ],
      en: [
        "200% Enhanced Damage",
        "+75% Damage To Undead",
        "Requirements -20%",
        "20% Increased Attack Speed",
        "+50 To Attack Rating Against Undead",
        "+2 To All Skills",
        "All Resistances +75",
        "20% Faster Hit Recovery",
        "11% Mana Stolen Per Hit",
        "Hit Causes Monster To Flee +25%",
        "Hit Blinds Target +33",
        "+2 To Mana After Each Kill",
        "30% Better Chance Of Getting Magic Items",
      ],
    },
    expansion: "lod",
    references: {
      es: "https://diablo.fandom.com/wiki/Silence_Rune_Word",
      en: "https://diablo.fandom.com/wiki/Silence_Rune_Word",
    },
  },
  infinity: {
    key: "infinity",
    runes: ["ber", "mal", "ber", "ist"],
    name: {
      es: "Infinito",
      en: "Infinity",
    },
    level: {
      es: "Nv. 63",
      en: "Lv. 63",
    },
    requires: {
      es: ["Armas de Asta", "Lanzas"],
      en: ["Polearms", "Lances"],
    },
    details: {
      es: [
        "50% de Lanzar Nivel 20 Cadena de Rayos al Matar un Monstruo",
        "Nivel 12 Aura Convicción Cuando esta Equipado",
        "+35% Correr/Andar mas Rápido",
        "+255-325% Daño Mejorado (varia)",
        "-(45-55)% para Resistencia al Rayo Enemigo",
        "40% Posibilidad de Golpe Triturador",
        "Evita la Curación del Monstruo",
        "+0-49 de Vitalidad (+0.5 por Nivel)",
        "+30% de Probabilidad de Encontrar Objetos Mágicos",
        "Nivel 21 Armadura Ciclón (30 Cargas)",
      ],
      en: [
        "50% Chance To Cast Level 20 Chain Lightning When You Kill An Enemy",
        "Level 12 Conviction Aura When Equipped",
        "+35% Faster Run/Walk",
        "+255-325% Enhanced Damage",
        "-(45-55)% To Enemy Lightning Resist",
        "+40% Chance of Crushing Blow",
        "Prevent Monster Heal",
        "0.5-49.5 To Vitality (Based on Character Level)",
        "30% Better Chance of Getting Magic Items",
        "Level 21 Cyclone Armor (30 Charges)",
      ],
    },
    expansion: "lod",
    references: {
      es: "https://diablo.fandom.com/wiki/Infinity_Rune_Word",
      en: "https://diablo.fandom.com/wiki/Infinity_Rune_Word",
    },
  },
  ground: {
    key: "ground",
    runes: ["shael", "io", "ort"],
    name: {
      es: "Tierra",
      en: "Ground",
    },
    level: {
      es: "Nv. 35",
      en: "Lv. 35",
    },
    requires: {
      es: ["Yelmos"],
      en: ["Helmets"],
    },
    details: {
      es: [
        "Recuperación de golpe un +20 % más rápida",
        "+75-100 % de defensa mejorada",
        "+10 p. de vitalidad",
        "Aumenta la vida máxima un 5 %",
        "+40-60 % de resistencia a los rayos",
        "+10-15 % de absorción de rayos",
      ],
      en: [
        "+20% Faster Hit Recovery",
        "+75-100% Enhanced Defense",
        "+10 to Vitality",
        "Increase Maximum Life 5%",
        "Lightning Resist +40-60%",
        "Lightning Absorb +10-15%",
      ],
    },
    expansion: "lod",
    references: {
      es: "https://diablo.fandom.com/wiki/Ground_Rune_Word",
      en: "https://diablo.fandom.com/wiki/Ground_Rune_Word",
    },
  },
  prudence: {
    key: "prudence",
    runes: ["mal", "tir"],
    name: {
      es: "Prudencia",
      en: "Prudence",
    },
    level: {
      es: "Nv. 49",
      en: "Lv. 49",
    },
    requires: {
      es: ["Armaduras"],
      en: ["Armors"],
    },
    details: {
      es: [
        "+25% Recuperación de Impacto Mas Rápida",
        "+140-170% Defensa Perfeccionada (varia)",
        "Todas las Resistencias +25-35 (varia)",
        "Daño Reducido en 3",
        "Daño de Magia Reducido en 17",
        "+2 Al mana Tras Cada Muerte",
        "+1 al Radio de Luz",
        "Repara 1 de Durabilidad en 4 Segundos",
      ],
      en: [
        "+25% Faster Hit Recovery",
        "+140-170% Enhanced Defense",
        "All Resistances +25-35",
        "Damage Reduced by 3",
        "Magic Damage Reduced by 17",
        "+2 To Mana After Each Kill",
        "+1 To Light Radius",
        "Repairs Durability 1 In 4 Seconds",
      ],
    },
    expansion: "lod",
    references: {
      es: "https://diablo.fandom.com/wiki/Prudence_Rune_Word",
      en: "https://diablo.fandom.com/wiki/Prudence_Rune_Word",
    },
  },
  breath_of_the_dying: {
    key: "breath_of_the_dying",
    runes: ["vex", "hel", "el", "eld", "zod", "eth"],
    name: {
      es: "Aliento De Los Muertos",
      en: "Breath of the Dying",
    },
    level: {
      es: "Nv. 69",
      en: "Lv. 69",
    },
    requires: {
      es: ["Armas"],
      en: ["Weapons"],
    },
    details: {
      es: [
        "50% Posibilidad de Lanzar el Nivel 20 Nova de Veneno Cuando mates un Enemigo",
        "Indestructible",
        "+60% Velocidad de Ataque aumentada",
        "+350-400% Daño Mejorado (varia)",
        "+200% Daño a Muertos Vivientes",
        "-25% Defensa del Objetivo",
        "+50 a la Puntuación de Ataque",
        "+50 a la Puntuación de Ataque Muertos Vivientes",
        "7% mana Robado Por Impacto",
        "12-15% Vida Robada por Impacto (varia)",
        "Evita la Curación del Monstruo",
        "+30 a Todos los Atributos",
        "+1 al Radio de Luz",
        "Requisitos -20%",
      ],
      en: [
        "50% Chance To Cast Level 20 Poison Nova When You Kill An Enemy",
        "Indestructible",
        "+60% Increased Attack Speed",
        "+350-400% Enhanced Damage (varies)",
        "+200% Damage To Undead",
        "-25% Target Defense",
        "+50 To Attack Rating",
        "+50 To Attack Rating Against Undead",
        "7% Mana Stolen per Hit",
        "12-15% Life Stolen per Hit",
        "Prevent Monster Heal",
        "+30 To All Attributes",
        "+1 To Light Radius",
        "Requirements -20%",
      ],
    },
    expansion: "lod",
    references: {
      es: "https://diablo.fandom.com/wiki/Breath_of_the_Dying_Rune_Word",
      en: "https://diablo.fandom.com/wiki/Breath_of_the_Dying_Rune_Word",
    },
  },
  spirit: {
    key: "spirit",
    runes: ["tal", "thul", "ort", "amn"],
    name: {
      es: "Espíritu",
      en: "Spirit",
    },
    level: {
      es: "Nv. 25",
      en: "Lv. 25",
    },
    requires: {
      es: ["Espadas", "Escudos"],
      en: ["Swords", "Shields"],
    },
    details_on: [
      {
        key: "sword",
        name: {
          es: "Espada",
          en: "Sword",
        },
        items: {
          es: [
            "+2 a todas las habilidades",
            "+(25-35)% Velocidad de Lanzamiento mas rápido (varia)",
            "+55% Recuperación de Impacto mas rápido",
            "Añade 1-50 Daño Relámpago",
            "Añade 3-14 Daño de Frio",
            "+75 Daño de Veneno Durante 5 Segundos",
            "7% Vida Robada por Impacto",
            "+250 Defensa contra Misiles",
            "+22 de Vitalidad",
            "+(89-112) de Mana (varia)",
            "+(3-8) Absorción de Magia (varia)",
          ],
          en: [
            "+2 To All Skills",
            "+25-35% Faster Cast Rate (varies)",
            "+55% Faster Hit Recovery",
            "+250 Defense vs. Missiles",
            "+22 To Vitality",
            "+89-112 To Mana (varies)",
            "+3-8 Magic Absorb (varies)",
            "+75 Poison Damage Over 5 Seconds",
            "Adds 3-14 Cold Damage",
            "Adds 1-50 Lightning Damage",
            "7% Life Stolen Per Hit",
          ],
        },
      },
      {
        key: "shield",
        name: {
          es: "Escudo",
          en: "Shield",
        },
        items: {
          es: [
            "+2 a Todas las Habilidades",
            "+(25-35)% Velocidad de Lanzamiento mas Rápido (varia)",
            "+55% Recuperación de Impacto mas Rápido",
            "+250 Defensa contra Misiles",
            "+22 de Vitalidad",
            "+(89-112) de Mana (varia)",
            "Resistencia a los Rayos 35%",
            "Resistencia al Frio 35%",
            "Resistencia al Veneno 35%",
            "+(3-8) Absorción de Magia (varia)",
            "El Atacante Recibe el Daño de 14",
          ],
          en: [
            "+2 To All Skills",
            "+25-35% Faster Cast Rate (varies)",
            "+55% Faster Hit Recovery",
            "+250 Defense vs. Missiles",
            "+22 To Vitality",
            "+89-112 To Mana (varies)",
            "+3-8 Magic Absorb (varies)",
            "Poison Resist +35%",
            "Cold Resist +35%",
            "Lightning Resist +35%",
            "Attacker Takes Damage of 14",
          ],
        },
      },
    ],
    expansion: "lod",
    references: {
      es: "https://diablo.fandom.com/wiki/Spirit_Rune_Word",
      en: "https://diablo.fandom.com/wiki/Spirit_Rune_Word",
    },
  },
  grief: {
    key: "grief",
    runes: ["eth", "tir", "lo", "mal", "ral"],
    name: {
      es: "Dolor",
      en: "Grief",
    },
    level: {
      es: "Nv. 59",
      en: "Lv. 59",
    },
    requires: {
      es: ["Hachas", "Espadas"],
      en: ["Axes", "Swords"],
    },
    details: {
      es: [
        "35% de Posibilidades de Lanzar el Nivel 15 Veneno al Recibir un Azote",
        "+30-40% Velocidad de Ataque Aumentada (varia)",
        "+340-400 Daño (varia)",
        "Ignorar Defensa del Objetivo",
        "-25% Defensa del Objetivo",
        "+1-185% Daño a Demonios (+1.875 por Nivel)",
        "Añade 5-30 Daño de Fuego",
        "-20-25% para Resistencia al Veneno Enemigo (varia)",
        "20% Azote Mortal",
        "Evita la Curación del Monstruo",
        "+2 al mana Tras Cada Muerte",
        "+10-15 Vida después de Cada Muerte",
      ],
      en: [
        "35% Chance To Cast Level 15 Venom On Striking",
        "+30-40% Increased Attack Speed",
        "Damage +340-400",
        "Ignore Target's Defense",
        "-25% Target Defense",
        "+(1.875 per character level) 1.875-185.625% Damage To Demons (Based on Character Level)",
        "Adds 5-30 Fire Damage",
        "-(20-25)% To Enemy Poison Resist",
        "+20% Deadly Strike",
        "Prevent Monster Heal",
        "+2 To Mana After Each Kill",
        "+10-15 Life After Each Kill",
      ],
    },
    expansion: "lod",
    references: {
      es: "https://diablo.fandom.com/wiki/Grief_Rune_Word",
      en: "https://diablo.fandom.com/wiki/Grief_Rune_Word",
    },
  },
  mosaic: {
    key: "mosaic",
    runes: ["mal", "gul", "amn"],
    name: {
      es: "Mosaico",
      en: "Mosaic",
    },
    level: {
      es: "Nv. 53",
      en: "Lv. 53",
    },
    requires: {
      es: ["Garras"],
      en: ["Katars"],
    },
    details: {
      es: [
        "+50% de probabilidad de que los remates no consuman cargas",
        "Cuando se ejecuta un remate de esta forma, ahora se reinicia el temporizador de reserva de la acumulación",
        "+2 p. a las artes marciales (solo asesina)",
        "+20% de velocidad de ataque",
        "+200-250% de daño mejorado (varia)",
        "+20% de bonus al índice de ataque",
        "7% de robo de vida",
        "+8-15% de daño con habilidades de frío",
        "+8-15% de daño con habilidades de rayos",
        "+8-15% de daño con habilidades de fuego",
        "Impide que los monstruos se curen",
      ],
      en: [
        "+50% chance for finishing moves to not consume charges",
        "When a finisher is executed this way, it now refreshes the expiration timer of the stack",
        "+2 to Martial Arts (Assassin only)",
        "+20% Increased Attack Speed",
        "+200-250% Enhanced Damage",
        "+20% Bonus to Attack Rating",
        "7% Life Steal",
        "8-15% to Cold Skill Damage",
        "8-15% to Lightning Skill Damage",
        "8-15% to Fire Skill Damage",
        "Prevent Monster Heal",
      ],
    },
    expansion: "lod",
    references: {
      es: "https://diablo.fandom.com/wiki/Mosaic_Rune_Word",
      en: "https://diablo.fandom.com/wiki/Mosaic_Rune_Word",
    },
  },
  destruction: {
    key: "destruction",
    runes: ["vex", "lo", "ber", "jah", "ko"],
    name: {
      es: "Destrucción",
      en: "Destruction",
    },
    level: {
      es: "Nv. 63",
      en: "Lv. 63",
    },
    requires: {
      es: ["Armas de Asta", "Espadas"],
      en: ["Polearms", "Swords"],
    },
    details: {
      es: [
        "23% de probabilidad de lanzar Nivel 12 Volcán al azotar",
        "5% de probabilidad de lanzar Nivel 23 Roca Ígnea al azotar",
        "100% de probabilidad de lanzar Nivel 45 Meteorito al morir",
        "15% de probabilidad de lanzar Nivel 22 Nova al atacar",
        "+350% Daño Mejorado",
        "Ignora la Defensa del Objetivo",
        "Añade 100-180 de Daño de Magia",
        "7% de maná robado por impacto",
        "20% Probabilidad de Golpe Triturador",
        "20% Azote Mortal",
        "Evita la Curación del Monstruo",
        "+10 de Destreza",
      ],
      en: [
        "23% Chance To Cast Level 12 Volcano On Striking",
        "5% Chance To Cast Level 23 Molten Boulder On Striking",
        "100% Chance To Cast Level 45 Meteor When You Die",
        "15% Chance To Cast Level 22 Nova On Attack",
        "+350% Enhanced Damage",
        "Ignore Target's Defense",
        "Adds 100-180 Magic Damage",
        "7% Mana Stolen Per Hit",
        "+20% Chance of Crushing Blow",
        "+20% Deadly Strike",
        "Prevent Monster Heal",
        "+10 To Dexterity",
      ],
    },
    expansion: "lod",
    references: {
      es: "https://diablo.fandom.com/wiki/Destruction_Rune_Word",
      en: "https://diablo.fandom.com/wiki/Destruction_Rune_Word",
    },
  },
  delirium: {
    key: "delirium",
    runes: ["lem", "ist", "io"],
    name: {
      es: "Delirio",
      en: "Delirium",
    },
    level: {
      es: "Nv. 51",
      en: "Lv. 51",
    },
    requires: {
      es: ["Yelmos"],
      en: ["Helmets"],
    },
    details: {
      es: [
        "1% Posibilidad de Lanzar el Nivel 50 Delirio al Recibir un Azote",
        "6% Posibilidad de Lanzar el Nivel 14 Ráfaga de Mente al Recibir un Azote",
        "14% Posibilidad de Lanzar el Nivel 13 Terror al Recibir un Azote",
        "11% Posibilidad de Lanzar el Nivel 18 Confundir al Azotar",
        "+2 a Todas las Habilidades",
        "+261 Defensa",
        "+10 de Vitalidad",
        "50% Oro Extra de los Monstruos",
        "+25% de Probabilidad de Encontrar Objetos Mágicos",
        "Nivel 17 Atracción (60 Cargas)",
      ],
      en: [
        "1% Chance To Cast Level 50 Delirium When Struck (morph)",
        "6% Chance To Cast Level 14 Mind Blast When Struck",
        "14% Chance To Cast Level 13 Terror When Struck",
        "11% Chance To Cast Level 18 Confuse On Striking",
        "+2 To All Skills",
        "+261 Defense",
        "+10 To Vitality",
        "50% Extra Gold From Monsters",
        "25% Better Chance of Getting Magic Items",
        "Level 17 Attract (60 Charges)",
      ],
    },
    expansion: "lod",
    references: {
      es: "https://diablo.fandom.com/wiki/Delirium_Rune_Word",
      en: "https://diablo.fandom.com/wiki/Delirium_Rune_Word",
    },
  },
  death: {
    key: "death",
    runes: ["hel", "el", "vex", "ort", "gul"],
    name: {
      es: "Muerte",
      en: "Death",
    },
    level: {
      es: "Nv. 63",
      en: "Lv. 63",
    },
    requires: {
      es: ["Espadas", "Hachas"],
      en: ["Swords", "Axes"],
    },
    details: {
      es: [
        "100% de probabilidad de lanzar Nivel 44 Cadena de Rayos al morir",
        "25% de probabilidad de lanzar Nivel 18 Pincho Glacial al atacar",
        "Indestructible",
        "+300-385% Daño Mejorado",
        "+20% Bonificación al Ataque",
        "+50 de Índice de Ataque",
        "Añade 1-50 de Daño de Relámpago",
        "7% de maná robado por impacto",
        "50% Probabilidad de Golpe Triturador",
        "+0-49% Azote Mortal (+0.5 por nivel)",
        "+1 al Radio de Luz",
        "Nivel 22 Golem de Sangre (15 cargas)",
        "Requisitos -20%",
      ],
      en: [
        "100% Chance To Cast Level 44 Chain Lightning When You Die",
        "25% Chance To Cast Level 18 Glacial Spike On Attack",
        "Indestructible",
        "+300-385% Enhanced Damage",
        "20% Bonus To Attack Rating",
        "+50 To Attack Rating",
        "Adds 1-50 Lightning Damage",
        "7% Mana Stolen Per Hit",
        "+50% Chance of Crushing Blow",
        "+(0.5 per Character Level) 0.5-49.5% Deadly Strike (Based on Character Level)",
        "+1 To Light Radius",
        "Level 22 Blood Golem (15 Charges)",
        "Requirements -20%",
      ],
    },
    expansion: "lod",
    references: {
      es: "https://diablo.fandom.com/wiki/Death_Rune_Word",
      en: "https://diablo.fandom.com/wiki/Death_Rune_Word",
    },
  },
  heart_of_the_oak: {
    key: "heart_of_the_oak",
    runes: ["ko", "vex", "pul", "thul"],
    name: {
      es: "Corazón De Roble",
      en: "Heart of The Oak",
    },
    level: {
      es: "Nv. 55",
      en: "Lv. 55",
    },
    requires: {
      es: ["Mazas", "Bastones"],
      en: ["Maces", "Staves"],
    },
    details: {
      es: [
        "+3 a Todas las Habilidades",
        "Velocidad de Lanzamiento +40%",
        "+75% de Daño contra Demonios",
        "+100 de Índice de Ataque contra Demonios",
        "Añade 3-14 de Daño de Frío (Duración 3 seg. en Normal)",
        "7% de maná robado por golpe",
        "+10 de Destreza",
        "Regeneración de Vida +20",
        "Aumenta el maná máximo un 15%",
        "+30-40 a Todas las Resistencias",
        "Sabio del Roble de Nivel 4 (25 cargas)",
        "Cuervo de Nivel 14 (60 cargas)",
      ],
      en: [
        "+3 To All Skills",
        "+40% Faster Cast Rate",
        "+75% Damage To Demons",
        "+100 To Attack Rating Against Demons",
        "Adds 3-14 Cold Damage, 3 sec. Duration (Normal)",
        "7% Mana Stolen Per Hit",
        "+10 To Dexterity",
        "Replenish Life +20",
        "Increase Maximum Mana 15%",
        "All Resistances +30-40",
        "Level 4 Oak Sage (25 Charges)",
        "Level 14 Raven (60 Charges)",
      ],
    },
    expansion: "lod",
    references: {
      es: "https://diablo.fandom.com/wiki/Heart_of_the_Oak_Rune_Word",
      en: "https://diablo.fandom.com/wiki/Heart_of_the_Oak_Rune_Word",
    },
  },
  bulwark: {
    key: "bulwark",
    runes: ["shael", "io", "sol"],
    name: {
      es: "Baluarte",
      en: "Bulwark",
    },
    level: {
      es: "Nv. 35",
      en: "Lv. 35",
    },
    requires: {
      es: ["Yelmos"],
      en: ["Helmets"],
    },
    details: {
      es: [
        "Recuperación de golpe un +20% más rápida",
        "+4-6% de vida robada por golpe (varia)",
        "+75-100% de defensa mejorada (varia)",
        "+10 p. de vitalidad",
        "Aumenta la vida máxima 5%",
        "+30 p. de regeneración de vida",
        "Daño reducido en +7 p.",
        "Daño físico sufrido reducido un 10-15% (varia)",
      ],
      en: [
        "+20% Faster Hit Recovery",
        "+4-6% Life stolen per hit",
        "+75-100% Enhanced Defense",
        "+10 to Vitality",
        "Increase Maximum Life 5%",
        "Replenish Life +30",
        "Damage Reduced by 7",
        "Physical Damage Received Reduced by 10-15%",
      ],
    },
    expansion: "lod",
    references: {
      es: "https://diablo.fandom.com/wiki/Bulwark_Rune_Word",
      en: "https://diablo.fandom.com/wiki/Bulwark_Rune_Word",
    },
  },
  steel: {
    key: "steel",
    runes: ["tir", "el"],
    name: {
      es: "Acero",
      en: "Steel",
    },
    level: {
      es: "Nv. 13",
      en: "Lv. 13",
    },
    requires: {
      es: ["Mazas", "Hachas", "Espadas"],
      en: ["Maces", "Axes", "Swords"],
    },
    details: {
      es: [
        "+20% Daño Mejorado",
        "+3 al Daño Mínimo",
        "+3 al Daño Máximo",
        "25% Velocidad de Ataque Aumentada",
        "50% Posibilidad de Heridas Abiertas",
        "+50 Puntuación de Ataque",
        "+2 al mana Tras Cada Muerte",
        "+1 al Radio de Luz",
      ],
      en: [
        "20% Enhanced Damage",
        "+3 To Minimum Damage",
        "+3 To Maximum Damage",
        "+50 To Attack Rating",
        "+50% Chance Of Open Wounds",
        "25% Increased Attack Speed",
        "+2 To Mana After Each Kill",
        "+1 To Light Radius",
      ],
    },
    expansion: "lod",
    references: {
      es: "https://diablo.fandom.com/wiki/Steel_Rune_Word",
      en: "https://diablo.fandom.com/wiki/Steel_Rune_Word",
    },
  },
  last_wish: {
    key: "last_wish",
    runes: ["jah", "mal", "jah", "sur", "jah", "ber"],
    name: {
      es: "Último Deseo",
      en: "Last Wish",
    },
    level: {
      es: "Nv. 65",
      en: "Lv. 65",
    },
    requires: {
      es: ["Martillos", "Hachas", "Espadas"],
      en: ["Hammers", "Axes", "Swords"],
    },
    details: {
      es: [
        "6% de posibilidades de lanzar el nivel 11 Fundido al recibir un azote",
        "10% de posibilidades de lanzar el nivel 18 Transfusión de Vida al azotar",
        "20% de posibilidades de lanzar el nivel 20 Descarga de Energía al atacar",
        "Nivel 17 Aura Poderío Cuando esta Equipado",
        "+330-375% Daño Mejorado (varia)",
        "Ignorar Defensa del Objetivo",
        "60-70% Posibilidad de Golpe Triturador (varia)",
        "Evita la Curación del Monstruo",
        "El Impacto Ciega al Objetivo",
        "+0-49 % de Probabilidad de Encontrar Objetos Mágicos [+0.5 por Nivel]",
      ],
      en: [
        "6% Chance To Cast Level 11 Fade When Struck",
        "10% Chance To Cast Level 18 Life Tap On Striking",
        "20% Chance To Cast Level 20 Charged Bolt On Attack",
        "Level 17 Might Aura When Equipped",
        "+330-375% Enhanced Damage",
        "Ignore Target's Defense",
        "+60-70% Chance of Crushing Blow",
        "Prevent Monster Heal",
        "Hit Blinds Target",
        "+(0.5 per character level) 0.5-49.5% Chance of Getting Magic Items (Based on Character Level)",
      ],
    },
    expansion: "lod",
    references: {
      es: "https://diablo.fandom.com/wiki/Last_Wish_Rune_Word",
      en: "https://diablo.fandom.com/wiki/Last_Wish_Rune_Word",
    },
  },
  hearth: {
    key: "hearth",
    runes: ["shael", "io", "thul"],
    name: {
      es: "Hogar",
      en: "Hearth",
    },
    level: {
      es: "Nv. 35",
      en: "Lv. 35",
    },
    requires: {
      es: ["Yelmos"],
      en: ["Helmets"],
    },
    details: {
      es: [
        "Recuperación de golpe un +20 % más rápida",
        "+75-100 % de defensa mejorada",
        "+10 p. de vitalidad",
        "Aumenta la vida máxima un 5 %",
        "+40-60 % de resistencia al frío",
        "+10-15 % de absorción de frío",
        "No te pueden congelar",
      ],
      en: [
        "+20% Faster Hit Recovery",
        "+75-100% Enhanced Defense",
        "+10 to Vitality",
        "Increase Maximum Life 5%",
        "Cold Resist +40-60%",
        "Cold Absorb +10-15%",
        "Cannot be Frozen",
      ],
    },
    expansion: "lod",
    references: {
      es: "https://diablo.fandom.com/wiki/Hearth_Rune_Word",
      en: "https://diablo.fandom.com/wiki/Hearth_Rune_Word",
    },
  },
  gloom: {
    key: "gloom",
    runes: ["fal", "um", "pul"],
    name: {
      es: "Melancolía",
      en: "Gloom",
    },
    level: {
      es: "Nv. 47",
      en: "Lv. 47",
    },
    requires: {
      es: ["Armaduras"],
      en: ["Armors"],
    },
    details: {
      es: [
        "15% Posibilidad de Lanzar el Nivel 3 Visión Borrosa al Recibir un Azote",
        "+10% Recuperación de Impacto Más Rápida",
        "+200-260% Defensa Mejorada (varía)",
        "+10 de Fuerza",
        "Todas las Resistencias +45",
        "Mitad de Duración del Congelamiento",
        "5% Daño Infligido Repercute en el mana",
        "-3 al Radio de Luz",
      ],
      en: [
        "15% Chance To Cast Level 3 Dim Vision When Struck",
        "+10% Faster Hit Recovery",
        "+200-260% Enhanced Defense",
        "+10 To Strength",
        "All Resistances +45",
        "Half Freeze Duration",
        "5% Damage Taken Goes To Mana",
        "-3 To Light Radius",
      ],
    },
    expansion: "lod",
    references: {
      es: "https://diablo.fandom.com/wiki/Gloom_Rune_Word",
      en: "https://diablo.fandom.com/wiki/Gloom_Rune_Word",
    },
  },
  exile: {
    key: "exile",
    runes: ["vex", "ohm", "ist", "dol"],
    name: {
      es: "Exilio",
      en: "Exile",
    },
    level: {
      es: "Nv. 57",
      en: "Lv. 57",
    },
    requires: {
      es: ["Escudos Paladín"],
      en: ["Paladín Shields"],
    },
    details: {
      es: [
        "15% Posibilidad de Lanzar el Nivel 5 Transfusión de Vida al Azotar",
        "Nivel 13-16 Aura Desafío Cuando está Equipado (varía)",
        "+2 a Auras Ofensivas (Solo Paladín)",
        "+30% Velocidad de Bloqueo",
        "Congela al Objetivo",
        "+220-260% Defensa Mejorada (varía)",
        "Regeneración de Vida +7",
        "+5% a la Resistencia Máxima al Frío",
        "+5% a la Resistencia Máxima al Fuego",
        "+25% Probabilidad de Encontrar Objetos Mágicos",
        "Repara 1 de Durabilidad Cada 4 Segundos",
      ],
      en: [
        "15% Chance To Cast Level 5 Life Tap On Striking",
        "Level 13-16 Defiance Aura When Equipped",
        "+2 To Offensive Auras (Paladin Only)",
        "+30% Faster Block Rate",
        "Freezes Target",
        "+220-260% Enhanced Defense (varies)",
        "Replenish Life +7",
        "+5% To Maximum Cold Resist",
        "+5% To Maximum Fire Resist",
        "25% Better Chance Of Getting Magic Items",
        "Repairs 1 Durability in 4 Seconds",
      ],
    },
    expansion: "lod",
    references: {
      es: "https://diablo.fandom.com/wiki/Exile_Rune_Word",
      en: "https://diablo.fandom.com/wiki/Exile_Rune_Word",
    },
  },
  phoenix: {
    key: "phoenix",
    runes: ["vex", "vex", "lo", "jah"],
    name: {
      es: "Fénix",
      en: "Phoenix",
    },
    level: {
      es: "Nv. 65",
      en: "Lv. 65",
    },
    requires: {
      es: ["Armas", "Escudos"],
      en: ["Weapons", "Shields"],
    },
    details_on: [
      {
        key: "weapon",
        name: {
          es: "Arma",
          en: "Weapon",
        },
        items: {
          es: [
            "100% de probabilidad de lanzar Nivel 40 Llamarada al subir de nivel",
            "40% de probabilidad de lanzar Nivel 22 Tormenta de Fuego al azotar",
            "Nivel 10-15 Aura Redención cuando está equipado",
            "+350-400% Daño Mejorado (varía)",
            "Ignora la Defensa del Objetivo (solo armas)",
            "14% de maná robado por impacto (solo armas)",
            "-28% a la Resistencia al Fuego del Enemigo",
            "+20% Azote Mortal (solo armas)",
            "+350-400 Defensa contra Misiles (varía)",
            "+15-21 Absorción de Fuego (varía)",
          ],
          en: [
            "100% Chance To Cast Level 40 Blaze When You Level-Up",
            "40% Chance To Cast Level 22 Firestorm On Striking",
            "Level 10-15 Redemption Aura When Equipped",
            "+350-400% Enhanced Damage",
            "Ignores Target's Defense",
            "14% Mana Stolen Per Hit",
            "-28% To Enemy Fire Resist",
            "+20% Deadly Strike",
            "+350-400 Defense vs. Missile",
            "+15-21 Fire Absorb",
          ],
        },
      },
      {
        key: "shield",
        name: {
          es: "Escudo",
          en: "Shield",
        },
        items: {
          es: [
            "100% de probabilidad de lanzar Nivel 40 Llamarada al subir de nivel",
            "40% de probabilidad de lanzar Nivel 22 Tormenta de Fuego al azotar",
            "Nivel 10-15 Aura Redención cuando está equipado (varía)",
            "+350-400% Daño Mejorado (varía)",
            "-28% a la Resistencia al Fuego del Enemigo",
            "+350-400 Defensa contra Misiles (varía)",
            "+50 de Vida (solo escudos)",
            "+5% a la Resistencia Máxima a los Relámpagos (solo escudos)",
            "+10% a la Resistencia Máxima al Fuego (solo escudos)",
            "+15-21 Absorción de Fuego (varía)",
          ],
          en: [
            "100% Chance To Cast Level 40 Blaze When You Level-Up",
            "40% Chance To Cast Level 22 Firestorm On Striking",
            "Level 10-15 Redemption Aura When Equipped",
            "+350-400 Defense vs. Missile",
            "+350-400% Enhanced Damage",
            "-28% To Enemy Fire Resist",
            "+50 To Life",
            "+5% To Maximum Lightning Resist",
            "+10% To Maximum Fire Resist",
            "+15-21 Fire Absorb",
          ],
        },
      },
    ],
    expansion: "lod",
    references: {
      es: "https://diablo.fandom.com/wiki/Phoenix_Rune_Word",
      en: "https://diablo.fandom.com/wiki/Phoenix_Rune_Word",
    },
  },
} as const;
